# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LmfahK2dL4ceVJZOe5Eb6IfKT/+4o2KM5gHhKSDj3GkBp7lbeKffe+eDiBrp1EaZwKCWs1DHYLHJ+1fD4a8g8X3nEmPSRN0+5Xr0jj57ZMMvZHPUCiv1xh6PfpdqYfbNP3W+LZsBAOKUi7UAa4+V3WyrQdyPhfg7Uu0XXE05Fx2EU1MBR9rag1suakUI/c4LHDiR6/N0qBm304+es4zzy0vuFbOEvqCiZaS2otpRwl6LpOL270qJef9m3ihYSCbUFo2RykV7ga1ocQ7RKaMEybk5RSA619WaPbSxWJ0F+FovpleW+Cz75MUUSDnBIDbDhp70M2EnZWc9uSn2o7aLbwWre6Prj/8eyMvvtn/5s3ObRmFpED4SecYVui6p6A8QX7R/6iFBXBUMsyMqEbWMraQ12oSciFsLuEB1XBOa2ZLVMJT7rG+IvPcIv5djLcMmo4h9u+u5Euxk8WercRTendkrRY+8rFxKzaK8+hU4y12ZrQNKlKHGFKgp5WmlWWVAclxmYUA3pEFEkTlYVdDPp2/unBKphy4VLDkCGPGQw6//m3Eu+20V8pAPyNFaeH2ORyp40Wz4eXWMjjjctNjvFfk2YUS9CXnbjeJy/9abmHt9eHbNiOPc6ZeAafJfU0B9YYJ7Gf9vrnrb0EQo90rx1QlADkgjQwwUzAAf1C2Y8bE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
