travis:
  secure:
    BINSTAR_TOKEN: LmfahK2dL4ceVJZOe5Eb6IfKT/+4o2KM5gHhKSDj3GkBp7lbeKffe+eDiBrp1EaZwKCWs1DHYLHJ+1fD4a8g8X3nEmPSRN0+5Xr0jj57ZMMvZHPUCiv1xh6PfpdqYfbNP3W+LZsBAOKUi7UAa4+V3WyrQdyPhfg7Uu0XXE05Fx2EU1MBR9rag1suakUI/c4LHDiR6/N0qBm304+es4zzy0vuFbOEvqCiZaS2otpRwl6LpOL270qJef9m3ihYSCbUFo2RykV7ga1ocQ7RKaMEybk5RSA619WaPbSxWJ0F+FovpleW+Cz75MUUSDnBIDbDhp70M2EnZWc9uSn2o7aLbwWre6Prj/8eyMvvtn/5s3ObRmFpED4SecYVui6p6A8QX7R/6iFBXBUMsyMqEbWMraQ12oSciFsLuEB1XBOa2ZLVMJT7rG+IvPcIv5djLcMmo4h9u+u5Euxk8WercRTendkrRY+8rFxKzaK8+hU4y12ZrQNKlKHGFKgp5WmlWWVAclxmYUA3pEFEkTlYVdDPp2/unBKphy4VLDkCGPGQw6//m3Eu+20V8pAPyNFaeH2ORyp40Wz4eXWMjjjctNjvFfk2YUS9CXnbjeJy/9abmHt9eHbNiOPc6ZeAafJfU0B9YYJ7Gf9vrnrb0EQo90rx1QlADkgjQwwUzAAf1C2Y8bE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
